server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VirtualAstroLab/astrolab-configurations
          searchPaths: config

info:
  app:
    name: astrolab-config-server
    type: Spring Boot (Config server)

management:
  endpoints:
    web:
      exposure:
        include: "*"

        